from django.contrib import admin
from django.urls import path
from fypapp.views import *

urlpatterns = [
    # path('', postdata.as_view()),
    path('signin',SIGNIN.as_view()),
    path('savedepi',savedirectorEPI.as_view()),
    path('countdepi',countdirectorEPI.as_view()),
    path('saveVaccineManager',saveVaccineManager.as_view()),
    path('countvacM', countvacM.as_view()),
    path('savehosp',savehospital.as_view()),
    path('counthosp',counthospital.as_view()),
    path('savemsi',savemedicalSuperIntendent.as_view()),
    path('countmsi',countmedicalSuperIntendent.as_view()),
    path('hospital_ids',HospitalIdsView.as_view()),
    path('getHospitalForDirectorEPI/',getHospitalForDirectorEPI.as_view()),
    path('countHospitalForDirectorEPI/',countHospitalForDirectorEPI.as_view()),
    path('savevac',savevaccine.as_view()),
    path('countvac',countvaccine.as_view()),
    path('saveVaccineAssignedToDirectorEPI',saveAssignedVaccinesToDirectorEPI.as_view()),
    path('countVaccineAssignedToDirectorEPI', countVaccineAssignedToDirectorEPI.as_view()),
    path('DirectorEPI_ids', DirectorEPI_IdsView.as_view()),
    path('Vaccine_IdsView', Vaccine_IdsView.as_view()),
    path('saveVaccineAssignedToHospital', saveVaccineAssignedToHospital.as_view()),
    path('countVaccineAssignedToHospital', countVaccineAssignedToHospital.as_view()),
    path('getProvinceOfDirectorEPI/', getProvinceOfDirectorEPI.as_view()),
    path('saveHCWAdmin', saveHCWAdmin.as_view()),
    path('countHealthCareWorkerAdmins', countHCWA.as_view()),
    path('saveVaccineAssignedToHealthCareWorkerAdmin', saveVaccineAssignedToHealthCareWorkerAdmin.as_view()),
    path('countVaccineAssignedToHealthCareWorkerAdmin', countVaccineAssignedToHealthCareWorkerAdmin.as_view()),
    path('getRegionOf_HCWA/', getRegionOf_HCWA.as_view()),
    path('savehcw',savehealthcareworker.as_view()),
    path('counthcw',counthealthcareworker.as_view()),
    path('saveVaccineAssignedToHCW',saveVaccineAssignedToHCW.as_view()),
    path('countVaccineAssignedToHCW',countVaccineAssignedToHCW.as_view()),
    path('getRegionOfHCWA/',getRegionOfHCWA.as_view()),
    # path('get_HCW_For_HCWA/',get_HCW_For_HCWA.as_view()),
    path('getHospitalIDofMSI/',getHospitalIDofMSI.as_view()),
    path('saveOperatingStaff', saveOperatingStaff.as_view()),
    path('countOperatingStaff', countOperatingStaff.as_view()),
    path('saveParent', saveParent.as_view()),
    path('saveBirthRecord', saveBirthRecord.as_view()),
    path('countBirthRecord', countBirthRecord.as_view()),
    path('savevacr',savevaccineRecord.as_view()),
    path('countvacr',countvaccineRecord.as_view()),
    path('getParentEmail/',getParentEmail.as_view()),
    path('getDEPIforVM/',getDEPIforVM.as_view()),
    path('CheckAssignmentView/',CheckAssignmentView.as_view()),
    path('getVacForVM/',getVacForVM.as_view()),
    path('updatingVacQuantity',updatingVacQuantity.as_view()),
    path('getVaccinesForDEPI/',getVaccinesForDEPI.as_view()),
    path('CheckAssignmentViewForHospital/',CheckAssignmentViewForHospital.as_view()),
    path('getVacForDEPI/',getVacForDEPI.as_view()),
    path('updatingVacQuantityForHospital',updatingVacQuantityForHospital.as_view()),
    path('CheckAssignmentViewForHCWA/',CheckAssignmentViewForHCWA.as_view()),
    path('updatingVacQuantityForHCWA',updatingVacQuantityForHCWA.as_view()),
    path('CheckAssignmentViewForHCW/',CheckAssignmentViewForHCW.as_view()),
    path('getVacForHCWA/',getVacForHCWA.as_view()),
    path('updatingVacQuantityForHCW',updatingVacQuantityForHCW.as_view()),
    path('getHospitalIDofOS/',getHospitalIDofOS.as_view()),
    path('CheckAssignmentViewForOSbirthRecord/',CheckAssignmentViewForOSbirthRecord.as_view()),
    path('getVacForHospital/',getVacForHospital.as_view()),
    path('getVaccQuantityOfHosp/',getVaccQuantityOfHosp.as_view()),
    path('RetrieveBirthRecordsForMSI/',RetrieveBirthRecordsForMSI.as_view()),
    path('saveFeedback',saveFeedback.as_view()),
    path('getPare/',getPare.as_view()),
    path('dpidashboard/',dpidashboard.as_view()),
      path('Vmdashboard/',Vmdashboard.as_view()),
        path('HCWAdashboard/',HCWAdashboard.as_view()),
         path('MSIAdashboard/',MSIAdashboard.as_view()),
           path('HCWAdashboard/',HCWAdashboard.as_view()),
            path('OPdashboard/',OPdashboard.as_view()),
    path('getBirthRecordsforParent/',getBirthRecordsforParent.as_view()),
    path('getVaccineRecordsforParent/',getVaccineRecordsforParent.as_view()),
    path('getVaccineAssignedToHospitalForOS/',getVaccineAssignedToHospitalForOS.as_view()),
    path('getVaccineAssignedToHCWA/',getVaccineAssignedToHCWA.as_view()),
    path('getVaccineAssignedToHCW/',getVaccineAssignedToHCW.as_view()),
    path('getVaccinesAssignedToHCWA_ForDEPI/',getVaccinesAssignedToHCWA_ForDEPI.as_view()),
    path('getHCWA_ForDEPI/',getHCWA_ForDEPI.as_view()),
    path('getVaccinesAssignedToHospital/',getVaccinesAssignedToHospital.as_view()),
    path('getHCWforHCWA/',getHCWforHCWA.as_view()),
    path('getVaccAssignedToHCWforHCWA/',getVaccAssignedToHCWforHCWA.as_view()),
    path('getVaccAssignedToMSI/',getVaccAssignedToMSI.as_view()),
    path('RetrieveOperatingStaffForMSI/',RetrieveOperatingStaffForMSI.as_view()),
    path('vaccinesForHCW/',vaccinesForHCW.as_view()),
    path('saveFutureVaccines',saveFutureVaccines.as_view()),
    path('GetFutureVaccinesForHCW/',GetFutureVaccinesForHCW.as_view()),
    path('CountFutureVaccines',CountFutureVaccines.as_view()),
    path('GetFutureVaccinesForParent/',GetFutureVaccinesForParent.as_view()),
]


