# Generated by Django 4.0 on 2023-05-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesslevel',
            fields=[
                ('email', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('access', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adminEmail', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adminPassword', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='birthRecord',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
                ('childWeight', models.FloatField(null=True)),
                ('childLength', models.FloatField(null=True)),
                ('deliveryType', models.CharField(max_length=25, null=True)),
                ('birth_date', models.CharField(max_length=200)),
                ('Hospital_ID', models.IntegerField(null=True)),
                ('RegisteredBy', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='directorEPI',
            fields=[
                ('directorEPIfullName', models.CharField(max_length=80)),
                ('directorEPIEmail', models.CharField(max_length=50, unique=True)),
                ('directorEPIPassword', models.CharField(max_length=20)),
                ('directorEPIProvince', models.CharField(max_length=25)),
                ('directorEPIphone', models.CharField(max_length=15, unique=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adminEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareWorkerAdmin',
            fields=[
                ('fullName', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=50, unique=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('directorEPI_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.directorepi', to_field='directorEPIEmail')),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalCity', models.CharField(max_length=100)),
                ('hospitalProvince', models.CharField(max_length=50)),
                ('hospitalAddress', models.CharField(max_length=150)),
                ('adminEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='medicalSuperIntendent',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('medicalSuperIntendentEmail', models.CharField(max_length=15, unique=True)),
                ('medicalSuperIntendentPassword', models.CharField(max_length=15)),
                ('medicalSuperIntendentFullName', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('adminEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.admin')),
                ('hospitalID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fypapp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Contact', models.CharField(max_length=15)),
                ('Mother_CNIC', models.CharField(max_length=20)),
                ('Father_Email', models.CharField(max_length=150, unique=True)),
                ('Password', models.CharField(max_length=15)),
                ('City', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineManager',
            fields=[
                ('VM_FullName', models.CharField(max_length=80)),
                ('VM_Email', models.CharField(max_length=50, unique=True)),
                ('VM_Password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=15)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adminEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccineName', models.CharField(max_length=50)),
                ('vaccinetype', models.CharField(max_length=50)),
                ('vaccinequantity', models.IntegerField()),
                ('vaccinedescription', models.CharField(max_length=255)),
                ('VM_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccinemanager', to_field='VM_Email')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingStaff',
            fields=[
                ('OS_fullName', models.CharField(max_length=80)),
                ('OS_Email', models.CharField(max_length=50, unique=True)),
                ('OS_Password', models.CharField(max_length=20)),
                ('OS_Contact', models.CharField(max_length=15)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.hospital')),
                ('MSI_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.medicalsuperintendent', to_field='medicalSuperIntendentEmail')),
            ],
        ),
        migrations.CreateModel(
            name='healthcareworker',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=150, unique=True)),
                ('Password', models.CharField(max_length=15)),
                ('fullName', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('HCWA_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.healthcareworkeradmin', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='future_vaccines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=100)),
                ('HCW_Email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fypapp.healthcareworker', to_field='Email')),
                ('OS_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.operatingstaff', to_field='OS_Email')),
                ('VaccineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccine')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.birthrecord')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Feedback_msg', models.CharField(max_length=250)),
                ('Father_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.parent', to_field='Father_Email')),
            ],
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='Father_CNIC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.parent'),
        ),
        migrations.CreateModel(
            name='vaccineRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('vaccination_Time', models.CharField(max_length=100, null=True)),
                ('RegisteredBy', models.CharField(max_length=150)),
                ('VaccineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccine')),
                ('childId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.birthrecord')),
            ],
            options={
                'unique_together': {('childId', 'VaccineId')},
            },
        ),
        migrations.CreateModel(
            name='VaccineAssignedToHospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Vaccine_Quantity', models.IntegerField()),
                ('DirectorEPI_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.directorepi', to_field='directorEPIEmail')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.hospital')),
                ('assigned_vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccine')),
            ],
            options={
                'unique_together': {('Hospital_ID', 'assigned_vaccine_id')},
            },
        ),
        migrations.CreateModel(
            name='VaccineAssignedToHealthCareWorkerAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Vaccine_Quantity', models.IntegerField()),
                ('assigned_vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccine')),
                ('directorEPI_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.directorepi', to_field='directorEPIEmail')),
                ('hcwAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.healthcareworkeradmin')),
            ],
            options={
                'unique_together': {('hcwAdminID', 'assigned_vaccine_id')},
            },
        ),
        migrations.CreateModel(
            name='vaccineAssignedToHCW',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Vaccine_Quantity', models.IntegerField()),
                ('HCWA_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.healthcareworkeradmin', to_field='email')),
                ('HCW_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.healthcareworker')),
                ('assigned_vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccine')),
            ],
            options={
                'unique_together': {('HCW_ID', 'assigned_vaccine_id')},
            },
        ),
        migrations.CreateModel(
            name='VaccineAssignedToDirectorEPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Vaccine_Quantity', models.IntegerField()),
                ('VM_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.vaccinemanager', to_field='VM_Email')),
                ('assigned_vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vaccine', to='fypapp.vaccine')),
                ('directorEPI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypapp.directorepi')),
            ],
            options={
                'unique_together': {('directorEPI_ID', 'assigned_vaccine_id')},
            },
        ),
    ]
